{
 "title": "Apache HTTP server logs",
 "tags": [ "apache-http-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Metrics datasource", "query": "prometheus" },
   { "name": "loki_datasource", "label": "Loki datasource", "query": "loki" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(apache_up,namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "query_result(count_over_time(apache_up{namespace=\"$namespace\"}[$__range]) > 0)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Error logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Logs by level",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({kubernetes_namespace_name=\"$namespace\", kubernetes_pod_name=\"$pod\"} | json | structured_logtype = `error` | structured_loglevel != `\"\"` [$__interval])) by (structured_loglevel)",
     "legendFormat": "{{ level }}"
    }
   ]
  },
  {
   "title": "Apache error logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{kubernetes_namespace_name=\"$namespace\", kubernetes_pod_name=\"$pod\"} | json | structured_logtype = `error` | structured_loglevel != `\"\"`"
    }
   ]
  },
  {
   "title": "Access logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Logs by HTTP codes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (le,namespace, pod) (\n  rate(\n    {kubernetes_namespace_name=~\"$namespace\",kubernetes_pod_name=\"$pod\"} | json | structured_code >= 100 and structured_code < 200 [1s]\n  )\n)",
     "legendFormat": "100-199"
    },
    {
     "expr": "sum by (le,namespace, pod) (\n  rate(\n    {kubernetes_namespace_name=~\"$namespace\",kubernetes_pod_name=\"$pod\"} | json | structured_code >= 200 and structured_code < 300 [1s]\n  )\n)",
     "legendFormat": "200-299"
    },
    {
     "expr": "sum by (namespace, pod) (\n  rate(\n    {kubernetes_namespace_name=~\"$namespace\",kubernetes_pod_name=\"$pod\"} | json | structured_code >= 400 and structured_code < 500 [1s]\n  )\n)",
     "legendFormat": "400-499"
    },
    {
     "expr": "sum by (le,namespace, pod) (\n  rate(\n    {kubernetes_namespace_name=~\"$namespace\",kubernetes_pod_name=\"$pod\"} | json | structured_code >= 500 and structured_code < 599 [1s]\n  )\n)",
     "legendFormat": "500-599"
    }
   ]
  },
  {
   "title": "Apache access logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{kubernetes_namespace_name=\"$namespace\", kubernetes_pod_name=\"$pod\"} | json | structured_logtype = `access`",
     "maxLines": 50
    }
   ]
  }
 ]
}