{
 "title": "Apache HTTP server",
 "tags": [ "apache-http-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(apache_up,namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "query_result(count_over_time(apache_up{namespace=\"$namespace\"}[$__range]) > 0)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apache_uptime_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apache_info{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Apache Up / Down",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "apache_up{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Apache up"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(apache_accesses_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "Calls"
    },
    {
     "expr": "rate(apache_sent_kilobytes_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) * 1000",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(apache_duration_ms_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])/increase(apache_accesses_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "Average response time"
    }
   ]
  },
  {
   "title": "Errors rate",
   "type": "timeseries",
   "description": "Ratio of 4xx and 5xx HTTP responses to all calls.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg by (le,namespace, pod)\n(\n(\n  increase(apache_response_http_codes_bucket{le=~\"499\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])\n- ignoring(le)\n  increase(apache_response_http_codes_bucket{le=~\"399\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])\n)\n/\nincrease(apache_response_http_codes_count{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) * 100\n)",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "Apache scoreboard statuses",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "apache_scoreboard{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Apache worker statuses",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "apache_workers{namespace=~\"$namespace\", pod=~\"$pod\"}\n",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Apache CPU load",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "apache_cpuload{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Load"
    }
   ]
  }
 ]
}