{{- if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    {{- include "httpd.selectorLabels" . | nindent 4 }}
  name: {{ include "httpd.fullname" . }}
spec:
spec:
  commonName: '{{ include "httpd.fullname" . | trunc 63 }}'
  dnsNames:
  - '{{ include "httpd.fullname" . }}.{{ .Release.Namespace }}.svc'
  - '{{ include "httpd.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local'
  - '{{ include "httpd.fullname" . }}-{{ .Release.Namespace }}.{{ .Values.domain }}'
  duration: 2160h0m0s
  issuerRef:
    {{- toYaml .Values.certManager.issuerRef | nindent 12 }}
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    rotationPolicy: Always
    size: 2048
  renewBefore: 360h0m0s
  secretName: {{ include "httpd.fullname" . }}-ssl
  secretTemplate:
    labels:
      {{- include "httpd.selectorLabels" . | nindent 6 }}
  subject:
    organizations:
    - Red Hat
  usages:
  - server auth
  - client auth
{{ end }}
